-- MySQL Script generated by MySQL Workbench
-- Mon Apr 25 13:53:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema opc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema opc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `opc` DEFAULT CHARACTER SET utf8mb4 ;
USE `opc` ;

-- -----------------------------------------------------
-- Table `opc`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opc`.`sensor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `data_type` VARCHAR(45) NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `created_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opc`.`crawl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opc`.`crawl` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sensor_id` INT NOT NULL,
  `data` LONGTEXT NULL,
  `filename` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_crawl_sensor_idx` (`sensor_id` ASC) VISIBLE,
  CONSTRAINT `fk_crawl_sensor`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `opc`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;